include:
  - remote: https://arp.to/@ci/docker.yml

update-by-schedules:
  only:
    - schedules
    - web
  script:
    - apk add git openssh-client ipcalc
    - ./scripts/generate.sh
    - bash ./scripts/commit.sh

update-by-changes:
  only:
    changes:
      - "*.yml"
      - "scripts/*.sh"
  except:
    - schedules
    - web
  script:
    - apk add git openssh-client ipcalc
    - ./scripts/generate.sh
    - bash ./scripts/commit.sh
